apiVersion: v1
kind: Service
metadata:
  namespace: web-stack
  name: node-exporter
  labels:
    app: node-exporter
spec:
  ports:
    - port: 9100
      targetPort: 9100
  selector:
    app: node-exporter