apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: web-stack
  labels:
    app: node-exporter
spec:
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    name: metrics
  selector:
    app: node-exporter