apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: web-stack
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: keep
            regex: 'node-exporter'
            source_labels:
              - '__meta_kubernetes_service_label_app'
