apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: web-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        fsGroup: 65534  # UID/GID pour les permissions
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        volumeMounts:
        - name: prometheus-storage
          mountPath: /prometheus  # Pour stocker les données de Prometheus
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml  # Fichier de config
          subPath: prometheus.yml  # Utilise le fichier spécifique du ConfigMap
      volumes:
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: prometheus-pvc  # PVC défini précédemment
      - name: prometheus-config
        configMap:
          name: prometheus-config  # Utilise le ConfigMap créé ci-dessus