apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - wordpress-deployment.yaml
  - wordpress-service.yaml
  - pvc-wordpress.yaml
  - pv-wordpress.yaml
  - secret_app_wp.yaml
  - namespace_app.yaml