apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  namespace: web-stack
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/wordpress"  # Chemin sur l'hôte où les données seront stockées