apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: pv-mysql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-mysql"