apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: pvc-mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi