apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:4.7.9-1
          ports:
            - containerPort: 8080
          env:
            - name: PMA_ARBITRARY
              value: "1"