name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build --platform=linux/amd64 -f ./docker/Dockerfile -t ghcr.io/Abdelbagui/Mini_projet_kubernets:$GITHUB_SHA ./app
          docker push ghcr.io/Abdelbagui/Mini_projet_kubernets:$GITHUB_SHA

  deploy_k8s:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Prepare K8s Deployment
        run: |
          export IMG_TAG="ghcr.io/Abdelbagui/Mini_projet_kubernets:$GITHUB_SHA"
          envsubst < kube/templates/deployment.yaml > kube/envs/prod/deployment.yaml

      - name: Commit and Push changes to K8S deployment
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update K8S Deployment [skip ci]"
          git push https://$CICD_TOKEN@github.com/Abdelbagui/Mini_projet_kubernets.git
