name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  # Build Docker image job
  build_docker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged # Required for Docker in Docker setup
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u docker --password-stdin registry.gitlab.com

      - name: Build Docker image
        run: docker build --platform=linux/amd64 -f ./docker/Dockerfile -t ${{ secrets.CI_REGISTRY_IMAGE }}:${{ github.sha }} ./app

      - name: Push Docker image
        run: docker push ${{ secrets.CI_REGISTRY_IMAGE }}:${{ github.sha }}

  # K8s deployment job
  deploy_k8s:
    needs: build_docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git gettext

      - name: Set image tag
        run: echo "IMG_TAG=${{ secrets.CI_REGISTRY_IMAGE }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Substitute variables in Kubernetes deployment
        run: envsubst < kube/templates/deployment.yaml > kube/envs/prod/deployment.yaml

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.CICD_TOKEN }}:${{ secrets.CICD_TOKEN }}@github.com/${{ github.repository }}

      - name: Checkout branch
        run: git checkout ${{ github.ref_name }}

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update K8S Deployment [skip ci]"
          git push origin HEAD:${{ github.ref_name }}
