name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Kubernetes context
        run: |
          az aks get-credentials --resource-group Abdel_ressource --name Abdel_cluster --overwrite-existing

      - name: Prepare K8s Deployment
        run: |
          # Appliquer les fichiers de configuration pour WordPress
          kubectl apply -f ./Front
          kubectl apply -f ./Back
          kubectl apply -f ./Back/Phpmyadmin
          kubectl apply -f ./Monitoring/Grafana
          kubectl apply -f ./Monitoring/Prometheus
          kubectl apply -f ./Monitoring/node-exporter  
          
